import { FaFacebookF,FaLinkedinIn, FaReact  } from "react-icons/fa";
import { FaXTwitter } from "react-icons/fa6";
import { ImAndroid } from "react-icons/im";
import { TbAdjustmentsCog } from "react-icons/tb";
import { MdOutlineSecurity } from "react-icons/md";
import { FaAws } from "react-icons/fa6";
import { CgFigma } from "react-icons/cg";
import Card from '../../../components/Card/Card'
import ndia from '../../../John.jpg'
import njeri from '../../../Victory.jpg'
import allan from '../../../Allan.jpg'
import bridget from '../../../Bridget.jpg'
import ruth from '../../../Ruth.jpg'
import webster from '../../../Webster.jpg'
import manase from '../../../Manase.jpg'
import carolyne from '../../../Carolyne.jpg'
import stanely from '../../../Stanley.jpg'
import paul from '../../../Paul.jpg'
import evyonne from '../../../Evyonne.jpg'
import './Lead.css'

function Lead() {
  return (
    <>
      <Card profile={ndia} socialsf={<FaFacebookF />} socialsx={<FaXTwitter />} socialsl={<FaLinkedinIn  />} lead="Dr. John Ndia" specialty="Patron of the Club" biography="This good man embodies the spirit of leadership that inspires us all. As the patron of our club, he is a guiding force, always prioritizing the success and growth of the team above all else. Whether it’s mentoring young minds, championing innovative ideas, or fostering a sense of unity among members, he consistently demonstrates the true essence of teamwork. " responsibilities="Dr. John Ndia is a source of unwavering support and encouragement to those around him. He is a pillar of strength in times of challenge and a wellspring of joy in moments of success for the tech club." web="Web Development" tool={<FaReact />} app="App Development" android={<ImAndroid />} platform="Platform Intergation" cross={<TbAdjustmentsCog />} security="Network Security" padlock={<MdOutlineSecurity />}/>

      <Card profile={njeri} socialsf={<FaFacebookF />} socialsx={<FaXTwitter />} socialsl={<FaLinkedinIn  />} lead="Victory Njeri" specialty="Chairperson of the Club" biography="This good lady embodies the spirit of leadership that inspires us all. As the Chairperson of our club, she is a guiding force, always prioritizing the success and growth of the team above all else. Whether it’s mentoring young minds, championing innovative ideas, or fostering a sense of unity among members, she consistently demonstrates the true essence of teamwork. " responsibilities="Victory Njeri is a source of unwavering support and encouragement to those around heer. She is a pillar of strength in times of challenge and a wellspring of joy in moments of success for the tech club." web="Web Development" tool={<FaReact />} ui="UI/UX Design" ux={<CgFigma />}app="App Development" android={<ImAndroid />} cloud="Cloud Engineering" storage={<FaAws />}/>

      <Card profile={allan} socialsf={<FaFacebookF />} socialsx={<FaXTwitter />} socialsl={<FaLinkedinIn  />} lead="Allan Muhari" specialty="Vice Chairperson of the Club" biography="This good man embodies the spirit of leadership that inspires us all. As the vice chairperson of our club, he is a guiding force, always prioritizing the success and growth of the team above all else. Whether it’s mentoring young minds, championing innovative ideas, or fostering a sense of unity among members, he consistently demonstrates the true essence of teamwork. " responsibilities="Allan Muhari is a source of unwavering support and encouragement to those around him. He is a pillar of strength in times of challenge and a wellspring of joy in moments of success for the tech club." cloud="Cloud Engineering" storage={<FaAws />} ui="UI/UX Design" ux={<CgFigma />} platform="Platform Intergation" cross={<TbAdjustmentsCog />} security="Network Security" padlock={<MdOutlineSecurity />}/>

      <Card profile={bridget} socialsf={<FaFacebookF />} socialsx={<FaXTwitter />} socialsl={<FaLinkedinIn  />} lead="Bridget Gitonga" specialty="Secretary of the Club" biography="This good lady embodies the spirit of leadership that inspires us all. As the secretary of our club, she is a guiding force, always prioritizing the success and growth of the team above all else. Whether it’s mentoring young minds, championing innovative ideas, or fostering a sense of unity among members, she consistently demonstrates the true essence of teamwork. " responsibilities="Bridget Gitonga is a source of unwavering support and encouragement to those around her. She is a pillar of strength in times of challenge and a wellspring of joy in moments of success for the tech club." security="Network Security" padlock={<MdOutlineSecurity />} platform="Platform Intergation" cross={<TbAdjustmentsCog />} cloud="Cloud Engineering" storage={<FaAws />} ui="UI/UX Design" ux={<CgFigma />}/>

      <Card profile={ruth} socialsf={<FaFacebookF />} socialsx={<FaXTwitter />} socialsl={<FaLinkedinIn  />} lead="Ruth Mutisya" specialty="Treasurer of the Club" biography="This good lady embodies the spirit of leadership that inspires us all. As treasure of our club, she is a guiding force, always prioritizing the success and growth of the team above all else. Whether it’s mentoring young minds, championing innovative ideas, or fostering a sense of unity among members, she consistently demonstrates the true essence of teamwork. " responsibilities="Ruth Mutisya is a source of unwavering support and encouragement to those around her. She is a pillar of strength in times of challenge and a wellspring of joy in moments of success for the tech club." web="Web Development" tool={<FaReact />} app="App Development" android={<ImAndroid />} platform="Platform Intergation" cross={<TbAdjustmentsCog />} security="Network Security" padlock={<MdOutlineSecurity />}/>

      <Card profile={webster} socialsf={<FaFacebookF />} socialsx={<FaXTwitter />} socialsl={<FaLinkedinIn  />} lead="Webster Ifedha" specialty="Cyber Security Lead" biography="This good man embodies the spirit of leadership that inspires us all. As the Cyber Security Lead, he is a guiding force, always prioritizing the success and growth of the team above all else. Whether it’s mentoring young minds, championing innovative ideas, or fostering a sense of unity among members, he consistently demonstrates the true essence of teamwork. " responsibilities="Webster Ifedha is a source of unwavering support and encouragement to those around him. He is a pillar of strength in times of challenge and a wellspring of joy in moments of success for the tech club." cloud="Cloud Engineering" storage={<FaAws />} ui="UI/UX Design" ux={<CgFigma />}platform="Platform Intergation" cross={<TbAdjustmentsCog />} security="Network Security" padlock={<MdOutlineSecurity />}/>

      <Card profile={manase} socialsf={<FaFacebookF />} socialsx={<FaXTwitter />} socialsl={<FaLinkedinIn  />} lead="Manase Gunga" specialty="UI/UX Design Lead" biography="This good man embodies the spirit of leadership that inspires us all. As the UI/UXdesign lead, he is a guiding force, always prioritizing the success and growth of the team above all else. Whether it’s mentoring young minds, championing innovative ideas, or fostering a sense of unity among members, he consistently demonstrates the true essence of teamwork. " responsibilities="Manase Gunga is a source of unwavering support and encouragement to those around him. He is a pillar of strength in times of challenge and a wellspring of joy in moments of success for the tech club." web="Web Development" tool={<FaReact />} app="App Development" android={<ImAndroid />} cloud="Cloud Engineering" storage={<FaAws />} ui="UI/UX Design" ux={<CgFigma />}/>

      <Card profile={carolyne} socialsf={<FaFacebookF />} socialsx={<FaXTwitter />} socialsl={<FaLinkedinIn  />} lead="Carolyne Githenduka" specialty="Web Development Lead" biography="This good lady embodies the spirit of leadership that inspires us all. As the web development lead, she is a guiding force, always prioritizing the success and growth of the team above all else. Whether it’s mentoring young minds, championing innovative ideas, or fostering a sense of unity among members, she consistently demonstrates the true essence of teamwork. " responsibilities="Carolyne Githenduka is a source of unwavering support and encouragement to those around her. She is a pillar of strength in times of challenge and a wellspring of joy in moments of success for the tech club." web="Web Development" tool={<FaReact />} app="App Development" android={<ImAndroid />} cloud="Cloud Engineering" storage={<FaAws />} ui="UI/UX Design" ux={<CgFigma />}/>

      <Card profile={stanely} socialsf={<FaFacebookF />} socialsx={<FaXTwitter />} socialsl={<FaLinkedinIn  />} lead="Stanely Amunze" specialty="Mobile App Development Lead" biography="This good man embodies the spirit of leadership that inspires us all. As the mobile app development lead, he is a guiding force, always prioritizing the success and growth of the team above all else. Whether it’s mentoring young minds, championing innovative ideas, or fostering a sense of unity among members, he consistently demonstrates the true essence of teamwork. " responsibilities="Stanely Amunze is a source of unwavering support and encouragement to those around him. He is a pillar of strength in times of challenge and a wellspring of joy in moments of success for the tech club." web="Web Development" tool={<FaReact />} app="App Development" android={<ImAndroid />} platform="Platform Intergation" cross={<TbAdjustmentsCog />} security="Network Security" padlock={<MdOutlineSecurity />}/>

      <Card profile={paul} socialsf={<FaFacebookF />} socialsx={<FaXTwitter />} socialsl={<FaLinkedinIn  />} lead="Paul Karanja" specialty="Cloud Engineering Lead" biography="This good man embodies the spirit of leadership that inspires us all. As the cloud engineering lead, he is a guiding force, always prioritizing the success and growth of the team above all else. Whether it’s mentoring young minds, championing innovative ideas, or fostering a sense of unity among members, he consistently demonstrates the true essence of teamwork. " responsibilities="Paul Karanja is a source of unwavering support and encouragement to those around him. He is a pillar of strength in times of challenge and a wellspring of joy in moments of success for the tech club." cloud="Cloud Engineering" storage={<FaAws />} ui="UI/UX Design" ux={<CgFigma />}platform="Platform Intergation" cross={<TbAdjustmentsCog />} security="Network Security" padlock={<MdOutlineSecurity />}/>

      <Card profile={evyonne} socialsf={<FaFacebookF />} socialsx={<FaXTwitter />} socialsl={<FaLinkedinIn  />} lead="Eyvonne Mbithe" specialty="Power Platform Lead" biography="This good lady embodies the spirit of leadership that inspires us all. As the Power Platform Lead, she is a guiding force, always prioritizing the success and growth of the team above all else. Whether it’s mentoring young minds, championing innovative ideas, or fostering a sense of unity among members, she consistently demonstrates the true essence of teamwork. " responsibilities="Eyvonne Mbithe is a source of unwavering support and encouragement to those around her. She is a pillar of strength in times of challenge and a wellspring of joy in moments of success for the tech club." web="Web Development" tool={<FaReact />} app="App Development" android={<ImAndroid />} platform="Platform Intergation" cross={<TbAdjustmentsCog />} security="Network Security" padlock={<MdOutlineSecurity />}/>
    </>
  )
}

export default Lead
