import { FaFacebookF,FaLinkedinIn, FaReact  } from "react-icons/fa";
import { FaXTwitter } from "react-icons/fa6";
import { ImAndroid } from "react-icons/im";
import { TbAdjustmentsCog } from "react-icons/tb";
import { MdOutlineSecurity } from "react-icons/md";
import { FaAws } from "react-icons/fa6";
import { CgFigma } from "react-icons/cg";
import Card from '../../../components/Card/Card'
import ndia from '../../../images/John.jpg'
import njeri from '../../../images/Victory.jpg'
import allan from '../../../images/Allan.jpg'
import bridget from '../../../images/Bridget.jpg'
import ruth from '../../../images/Ruth.jpg'
import webster from '../../../images/Webster.jpg'
import manase from '../../../images/Manase.jpg'
import carolyne from '../../../images/Carolyne.jpg'
import stanely from '../../../images/Stanley.jpg'
import paul from '../../../images/Paul.jpg'
import evyonne from '../../../images/Evyonne.jpg'
import './Lead.css'

function Lead() {
  return (
    <>
      <Card profile={ndia} socialsf={<FaFacebookF />} socialsx={<FaXTwitter />} socialsl={<FaLinkedinIn  />} lead="Dr. John Ndia" specialty="Patron of the Club" biography="This good man embodies the spirit of leadership that inspires us all. As the patron of our club, he is a guiding force, always prioritizing the success and growth of the team above all else. Whether it’s mentoring young minds, championing innovative ideas, or fostering a sense of unity among members, he consistently demonstrates the true essence of teamwork. " responsibilities="Dr. John Ndia is a source of unwavering support and encouragement to those around him. He is a pillar of strength in times of challenge and a wellspring of joy in moments of success for the tech club." web="Web Development" tool={<FaReact />} app="App Development" android={<ImAndroid />} platform="Platform Intergation" cross={<TbAdjustmentsCog />} security="Network Security" padlock={<MdOutlineSecurity />}/>

      <Card profile={njeri} socialsf={<FaFacebookF />} socialsx={<FaXTwitter />} socialsl={<FaLinkedinIn  />} lead="Victory Njeri" specialty="Chairperson of the Club" biography="This good lady embodies the spirit of leadership that inspires us all. As the patron of our club, she is a guiding force, always prioritizing the success and growth of the team above all else. Whether it’s mentoring young minds, championing innovative ideas, or fostering a sense of unity among members, he consistently demonstrates the true essence of teamwork. " responsibilities="Dr. John Ndia is a source of unwavering support and encouragement to those around him. He is a pillar of strength in times of challenge and a wellspring of joy in moments of success for the tech club." web="Web Development" tool={<FaReact />} app="App Development" android={<ImAndroid />} platform="Platform Intergation" cross={<TbAdjustmentsCog />} security="Network Security" padlock={<MdOutlineSecurity />}/>

      <Card profile={allan} socialsf={<FaFacebookF />} socialsx={<FaXTwitter />} socialsl={<FaLinkedinIn  />} lead="Dr. John Ndia" specialty="Patron of the Club" biography="This good man embodies the spirit of leadership that inspires us all. As the patron of our club, he is a guiding force, always prioritizing the success and growth of the team above all else. Whether it’s mentoring young minds, championing innovative ideas, or fostering a sense of unity among members, he consistently demonstrates the true essence of teamwork. " responsibilities="Dr. John Ndia is a source of unwavering support and encouragement to those around him. He is a pillar of strength in times of challenge and a wellspring of joy in moments of success for the tech club." web="Web Development" tool={<FaReact />} app="App Development" android={<ImAndroid />} platform="Platform Intergation" cross={<TbAdjustmentsCog />} security="Network Security" padlock={<MdOutlineSecurity />}/>

      <Card profile={bridget} socialsf={<FaFacebookF />} socialsx={<FaXTwitter />} socialsl={<FaLinkedinIn  />} lead="Dr. John Ndia" specialty="Patron of the Club" biography="This good man embodies the spirit of leadership that inspires us all. As the patron of our club, he is a guiding force, always prioritizing the success and growth of the team above all else. Whether it’s mentoring young minds, championing innovative ideas, or fostering a sense of unity among members, he consistently demonstrates the true essence of teamwork. " responsibilities="Dr. John Ndia is a source of unwavering support and encouragement to those around him. He is a pillar of strength in times of challenge and a wellspring of joy in moments of success for the tech club." web="Web Development" tool={<FaReact />} app="App Development" android={<ImAndroid />} platform="Platform Intergation" cross={<TbAdjustmentsCog />} security="Network Security" padlock={<MdOutlineSecurity />}/>

      <Card profile={ruth} socialsf={<FaFacebookF />} socialsx={<FaXTwitter />} socialsl={<FaLinkedinIn  />} lead="Dr. John Ndia" specialty="Patron of the Club" biography="This good man embodies the spirit of leadership that inspires us all. As the patron of our club, he is a guiding force, always prioritizing the success and growth of the team above all else. Whether it’s mentoring young minds, championing innovative ideas, or fostering a sense of unity among members, he consistently demonstrates the true essence of teamwork. " responsibilities="Dr. John Ndia is a source of unwavering support and encouragement to those around him. He is a pillar of strength in times of challenge and a wellspring of joy in moments of success for the tech club." web="Web Development" tool={<FaReact />} app="App Development" android={<ImAndroid />} platform="Platform Intergation" cross={<TbAdjustmentsCog />} security="Network Security" padlock={<MdOutlineSecurity />}/>

      <Card profile={webster} socialsf={<FaFacebookF />} socialsx={<FaXTwitter />} socialsl={<FaLinkedinIn  />} lead="Dr. John Ndia" specialty="Patron of the Club" biography="This good man embodies the spirit of leadership that inspires us all. As the patron of our club, he is a guiding force, always prioritizing the success and growth of the team above all else. Whether it’s mentoring young minds, championing innovative ideas, or fostering a sense of unity among members, he consistently demonstrates the true essence of teamwork. " responsibilities="Dr. John Ndia is a source of unwavering support and encouragement to those around him. He is a pillar of strength in times of challenge and a wellspring of joy in moments of success for the tech club." web="Web Development" tool={<FaReact />} app="App Development" android={<ImAndroid />} platform="Platform Intergation" cross={<TbAdjustmentsCog />} security="Network Security" padlock={<MdOutlineSecurity />}/>

      <Card profile={manase} socialsf={<FaFacebookF />} socialsx={<FaXTwitter />} socialsl={<FaLinkedinIn  />} lead="Dr. John Ndia" specialty="Patron of the Club" biography="This good man embodies the spirit of leadership that inspires us all. As the patron of our club, he is a guiding force, always prioritizing the success and growth of the team above all else. Whether it’s mentoring young minds, championing innovative ideas, or fostering a sense of unity among members, he consistently demonstrates the true essence of teamwork. " responsibilities="Dr. John Ndia is a source of unwavering support and encouragement to those around him. He is a pillar of strength in times of challenge and a wellspring of joy in moments of success for the tech club." web="Web Development" tool={<FaReact />} app="App Development" android={<ImAndroid />} platform="Platform Intergation" cross={<TbAdjustmentsCog />} security="Network Security" padlock={<MdOutlineSecurity />}/>

      <Card profile={carolyne} socialsf={<FaFacebookF />} socialsx={<FaXTwitter />} socialsl={<FaLinkedinIn  />} lead="Dr. John Ndia" specialty="Patron of the Club" biography="This good man embodies the spirit of leadership that inspires us all. As the patron of our club, he is a guiding force, always prioritizing the success and growth of the team above all else. Whether it’s mentoring young minds, championing innovative ideas, or fostering a sense of unity among members, he consistently demonstrates the true essence of teamwork. " responsibilities="Dr. John Ndia is a source of unwavering support and encouragement to those around him. He is a pillar of strength in times of challenge and a wellspring of joy in moments of success for the tech club." web="Web Development" tool={<FaReact />} app="App Development" android={<ImAndroid />} platform="Platform Intergation" cross={<TbAdjustmentsCog />} security="Network Security" padlock={<MdOutlineSecurity />}/>

      <Card profile={stanely} socialsf={<FaFacebookF />} socialsx={<FaXTwitter />} socialsl={<FaLinkedinIn  />} lead="Dr. John Ndia" specialty="Patron of the Club" biography="This good man embodies the spirit of leadership that inspires us all. As the patron of our club, he is a guiding force, always prioritizing the success and growth of the team above all else. Whether it’s mentoring young minds, championing innovative ideas, or fostering a sense of unity among members, he consistently demonstrates the true essence of teamwork. " responsibilities="Dr. John Ndia is a source of unwavering support and encouragement to those around him. He is a pillar of strength in times of challenge and a wellspring of joy in moments of success for the tech club." web="Web Development" tool={<FaReact />} app="App Development" android={<ImAndroid />} platform="Platform Intergation" cross={<TbAdjustmentsCog />} security="Network Security" padlock={<MdOutlineSecurity />}/>

      <Card profile={paul} socialsf={<FaFacebookF />} socialsx={<FaXTwitter />} socialsl={<FaLinkedinIn  />} lead="Dr. John Ndia" specialty="Patron of the Club" biography="This good man embodies the spirit of leadership that inspires us all. As the patron of our club, he is a guiding force, always prioritizing the success and growth of the team above all else. Whether it’s mentoring young minds, championing innovative ideas, or fostering a sense of unity among members, he consistently demonstrates the true essence of teamwork. " responsibilities="Dr. John Ndia is a source of unwavering support and encouragement to those around him. He is a pillar of strength in times of challenge and a wellspring of joy in moments of success for the tech club." web="Web Development" tool={<FaReact />} app="App Development" android={<ImAndroid />} platform="Platform Intergation" cross={<TbAdjustmentsCog />} security="Network Security" padlock={<MdOutlineSecurity />}/>
      <Card profile={evyonne} socialsf={<FaFacebookF />} socialsx={<FaXTwitter />} socialsl={<FaLinkedinIn  />} lead="Dr. John Ndia" specialty="Patron of the Club" biography="This good man embodies the spirit of leadership that inspires us all. As the patron of our club, he is a guiding force, always prioritizing the success and growth of the team above all else. Whether it’s mentoring young minds, championing innovative ideas, or fostering a sense of unity among members, he consistently demonstrates the true essence of teamwork. " responsibilities="Dr. John Ndia is a source of unwavering support and encouragement to those around him. He is a pillar of strength in times of challenge and a wellspring of joy in moments of success for the tech club." web="Web Development" tool={<FaReact />} app="App Development" android={<ImAndroid />} platform="Platform Intergation" cross={<TbAdjustmentsCog />} security="Network Security" padlock={<MdOutlineSecurity />}/>
    </>
  )
}

export default Lead
